### PR TITLE
Fix colliding patterns for StudioCalcAttachments

### PR DESCRIPTION
**Pull request by hobokenn**

### CODE REVIEW

**Comment by YaLTeR** [comment]
Hm, why reorder? Makes the diff harder to understand.

**Comment by hobokenn** [comment]
> 
> 
> Hm, why reorder? Makes the diff harder to understand.

to not write this code twice:
```
ORIG_VectorTransform = reinterpret_cast<_VectorTransform>(
	*reinterpret_cast<uintptr_t*>(reinterpret_cast<uintptr_t>(ORIG_StudioCalcAttachments) + 101)
	+ reinterpret_cast<uintptr_t>(ORIG_StudioCalcAttachments) + 105);
```

**Comment by YaLTeR** [comment]
ah oc

**Comment by YaLTeR** [comment]
Thanks

**Pull request merged**
