### PR TITLE
Added clientside VectorTransform for Condition Zero: Deleted Sc…

### PR DESCRIPTION
**Pull request by SmileyAG**
…enes

### CODE REVIEW

**Comment by YaLTeR** [comment]
Ty

**Comment by hobokenn** [comment]
oops, probably should've told you to not merge this until smiley makes changes

**Comment by YaLTeR** [comment]
Perhaps a draft MR would've helped here

**Comment by SmileyAG** [comment]
> 
> 
> oops, probably should've told you to not merge this until smiley makes changes

If i wanted to make more changes, I most likely did that PR was draft as YaLTeR said, if you are talking about resetting default_fov to 90 in CSCZDS, then I was planning to do it in another PR

**Comment by hobokenn** [comment]
check PRs in your fork)

**Comment by SmileyAG** [comment]
> 
> 
> check PRs in your fork)

oops, I noticed it only now 😄

**Pull request merged**
