### PR TITLE
Fix bxt_autorecord crash in Blue Shift on Linux

### LINKED ISSUE #239: `bxt_autorecord` (`fullupdate`) crashes Blue Shift on Linux
Probably same as #216
1) Load map 2) bxt_autorecord bla 3) crash.
* Doesn't happen on Opposing Force / Half-Life.
* Server/Client binaries used: https://www.speedrun.com/resourceasset/vsxva
* Don't think the binaries matter though. 
* Latest master
* BXT tagged release from Aug works fine 

EDIT:more info in smiley's PR
```c++
#0  CBasePlayer::UpdateClientData (this=0x9c6bf30) at ../blueshift/dlls/player.cpp:4163
#1  0xe90f2fd7 in ServerDLL::HOOKED_ClientCommand_Func (this=0xe95b7160 <ServerDLL::GetInstance()::instance>, pEntity=0xbb11076c) at /home/unko/repos/BunnymodXT/BunnymodXT/modules/ServerDLL.cpp:1863
#2  0xe90f2eca in ServerDLL::HOOKED_ClientCommand (pEntity=0xbb11076c) at /home/unko/repos/BunnymodXT/BunnymodXT/modules/ServerDLL.cpp:1832
#3  0xe90eb381 in ClientCommand (pEntity=0xbb11076c) at /home/unko/repos/BunnymodXT/BunnymodXT/modules/ServerDLL.cpp:50
#4  0xe6ed9f8e in SV_FullUpdate_f () at ../engine/sv_user.c:2316
#5  0xe6e738de in Cmd_ExecuteStringWithPrivilegeCheck (text=0xe705f960 <string> "fullupdate", bIsPrivileged=<optimized out>, src=<optimized out>) at ../engine/cmd.c:1257
#6  0xe6ed69c6 in SV_ParseStringCommand (pSenderClient=0xbb000598) at ../engine/sv_user.c:1753
#7  0xe6ed9e65 in SV_ExecuteClientMessage (cl=0xbb000598) at ../engine/sv_user.c:2226
#8  0xe6ecbe33 in SV_ReadPackets () at ../engine/sv_main.c:4976
#9  0xe6ecc0ae in SV_Frame () at ../engine/sv_main.c:9350
#10 0xe9088f8c in HwDLL::HOOKED_SV_Frame_Func (this=0xe95b63a0 <HwDLL::GetInstance()::instance>) at /home/unko/repos/BunnymodXT/BunnymodXT/modules/HwDLL.cpp:4856
#11 0xe9088ee9 in HwDLL::HOOKED_SV_Frame () at /home/unko/repos/BunnymodXT/BunnymodXT/modules/HwDLL.cpp:4848
#12 0xe90768da in SV_Frame () at /home/unko/repos/BunnymodXT/BunnymodXT/modules/HwDLL.cpp:80
#13 0xe6e8b7c6 in _Host_Frame (time=0.0180124771) at ../engine/host.c:1430
#14 0xe6e8bc52 in Host_Frame (time=0.0180124771, iState=4, stateInfo=0xffbfb15c) at ../engine/host.c:1548
#15 0xe6eb8b04 in CEngine::Frame (this=0xe70d2aa0 <g_Engine>) at ../engine/sys_engine.cpp:245
#16 0xe6eb658b in RunListenServer (instance=0x0, basedir=0x804b220 <szBaseDir> ".", cmdline=0x8bfc860 "./hl_linux -steam -game bshift", postRestartCmdLineArgs=0x804d360 <main::szNewCommandParams> "", launcherFactory=0x8049350 <CreateInterfaceLocal(char const*, int*)>, filesystemFactory=
    0xe80f3d40 <CreateInterface(char const*, int*)>) at ../engine/sys_dll2.cpp:955
#17 0x08048d67 in main (argc=4, argv=0xffbfb3a4) at ../launcher/launcher.cpp:439
```

### PR DESCRIPTION
**Pull request by SmileyAG**
Closes #239

### CODE REVIEW

**Comment by chinese-soup** [comment]
Tested the commit on my machine, fixes the mentioned issue on
```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:53:35 Aug  3 2020 (8684)
```

Smiley found that it was introduced here https://github.com/YaLTeR/BunnymodXT/pull/205

**Comment by YaLTeR** [comment]
Thanks!

**Comment by hobokenn** [comment]
> EDIT: Works both on the latest ServerDLL

it doesn't work on latest server.dll, it just doesn't crash, the ammo HUD is still reset on record

**Comment by chinese-soup** [comment]
> it doesn't work on latest server.dll, it just doesn't crash, the ammo HUD is still reset on record

Does it matter, tho? Who would use a version of Bshift that has speedrunning tricks fixed?

**Comment by hobokenn** [comment]
it doesn't really matter, i'm just mentioning it

**Comment by chinese-soup** [comment]
Alright. I guess this means it will now crash if you try to downgrade the HL1 and Op4 serverDLLs to the pre-yaw turn speed fix as well?

**Pull request merged**
