### PR TITLE
"injected" sounds weird imo

### PR DESCRIPTION
**Pull request by Nalexa-1124**

### CODE REVIEW

**Comment by YaLTeR** [comment]
It is **the** term used for this.

**Comment by Nalexa-1124** [comment]
Okay then.
Sorry I wasn't aware of the plugin naming society xD

**Comment by mikesmiffy128** [comment]
There's no society. DLL Injection is a long-established name given to the act of forcing another program to run your code - in other words, injecting the code into that process. It's just what it's called.

**Comment by Nalexa-1124** [comment]
I thought DLL meant dynamic link library

**Comment by mikesmiffy128** [comment]
Yes. It does indeed mean that. BXT is distributed as a DLL (or SO on Linux). Hence you inject that DLL into the hl.exe process, giving rise to the term "DLL Injection." 🤔

**Comment by Nalexa-1124** [comment]
That's kinda sad. I liked the society better.

**Comment by Traderain** [comment]
image

**Pull request closed without merging**
