### PR TITLE
Adding AXN style stuffs for CS1.6

### PR DESCRIPTION
**Pull request by khanghugo**
Just a stamina-related cvar to remove its effect on jump height and slow down.

Also bhop cap pattern for CS1.6. Not sure if I am doing the right way. Yet to test on Windows but I think this would work just fine.

### CODE REVIEW

**Comment by khanghugo** [comment]
Pattern `D8 88 F4 01 00 00` repeats sometimes for both Windows and Linux binary. I guess I can make this less verbose a bit.

**Comment by khanghugo** [comment]
Whoops, just realize the `pBhopcapWindows` patches different instruction. I don't want to complicate that.

**Comment by khanghugo** [comment]
I have not tested any TAS related things so let's see.

**Comment by khanghugo** [comment]
All works great. Now it is possible to do hlkz map in cs now, or just plain old axn maps

**Comment by YaLTeR** [comment]
Thanks!

**Pull request merged**
