### PR TITLE
Added bxt_viewmodel_semitransparent

### PR DESCRIPTION
**Pull request by SmileyAG**
Based on code from bunnymod-pro: https://github.com/YaLTeR/bunnymod-pro/blob/master/cl_dll/StudioModelRenderer.cpp#L1558-L1566

`bxt_viewmodel_semitransparent 1`:

изображение

### CODE REVIEW

**Comment by YaLTeR** [comment]
`bxt_viewmodel_opacity` reads like something that controls the... opacity of the viewmodel. So at 0.5 it would be half transparent and at 0 it would be completely invisible.

**Comment by SmileyAG** [comment]
> `bxt_viewmodel_opacity` reads like something that controls the... opacity of the viewmodel. So at 0.5 it would be half transparent and at 0 it would be completely invisible.

Hmm, maybe it's better rename it to like `bxt_viewmodel_half_opacity` and change boolean priority in functions? (0/1 instead of 1/0)

**Comment by YaLTeR** [comment]
Why is this needed actually?

**Comment by SmileyAG** [comment]
> Why is this needed actually?

If someone's want a transparent models without modifying weapon .mdl, same reason as we had a `bxt_viewmodel_disable_` cvars.

**Comment by YaLTeR** [comment]
> If someone's want a transparent models

Does someone want?

**Comment by SmileyAG** [comment]
> > If someone's want a transparent models
> 
> Does someone want?

`¯\_(ツ)_/¯`

**Comment by SmileyAG** [comment]
@YaLTeR Can be it merged now?

**Comment by YaLTeR** [comment]
Alright, just call it `bxt_viewmodel_semitransparent` maybe

**Comment by YaLTeR** [comment]
Thanks

**Pull request merged**
