### PR TITLE
Added bxt_remove_punchangles

### LINKED ISSUE #368: bxt_remove_punchangles

### PR DESCRIPTION
**Pull request by SmileyAG**
Closes #368

### CODE REVIEW

**Comment by khanghugo** [comment]
wtf, I was gonna do thisXd

**Comment by khanghugo** [comment]
Very nice

**Comment by khanghugo** [comment]
Alright, this works great on HL and CS Linux :+1: 
I am wondering if this should be enabled without `sv_cheats`.

**Comment by YaLTeR** [comment]
Thanks

**Pull request merged**
